image: "lava test"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - mkdir build && cd build
  - ls
  - cmake --version
  - export CC=clang CXX=clang++ LD=clang
  - cmake -DCMAKE_BUILD_TYPE=Debug .. && make

run_test:
  script:
    - cd ../test/
    - ls
    - ./run.py -l ../build/lacc
